services:
  postgres:
    image: supabase/postgres:17.4.1.032
    restart: always
    profiles: ["db", "local"] # Runs only when it's need
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  website:
    build: .
    profiles: ["web", "local"]
    environment:
      PRIVATE_PG_USER: ${PRIVATE_PG_USER:-admin} # Modified this line
      PRIVATE_PG_HOST: ${PRIVATE_PG_HOST:-postgres} # Modified this line
      PRIVATE_PG_DATABASE: ${PRIVATE_PG_DATABASE:-postgres} # Modified this line
      PRIVATE_PG_PASSWORD: ${PRIVATE_PG_PASSWORD:-password} # Modified this line
      PRIVATE_EMAIL: ${PRIVATE_EMAIL:-me@itsrofly.com}
      PRIVATE_EMAIL_API: ${PRIVATE_EMAIL_API:-https://unsend.itsrofly.com/api}
      PRIVATE_EMAIL_CONTACT_ID: ${PRIVATE_EMAIL_CONTACT_ID:-cmcggzo0a0006s4306syenex0}
      PRIVATE_EMAIL_ACCESS_KEY: ${PRIVATE_EMAIL_ACCESS_KEY}
      PRIVATE_WEBSITE_URL: ${PRIVATE_WEBSITE_URL:-https://itsrofly.com}
    ports:
      - "4000:4000"
    restart: always

volumes:
  postgres_data:
