services:
  postgres:
    image: postgres:latest
    restart: always
    profiles: ["local"] # Added this line
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  website:
    build: .
    environment:
      PRIVATE_PG_USER: ${PRIVATE_PG_USER:-admin} # Modified this line
      PRIVATE_PG_HOST: ${PRIVATE_PG_HOST:-postgres} # Modified this line
      PRIVATE_PG_DATABASE: ${PRIVATE_PG_DATABASE:-mydb} # Modified this line
      PRIVATE_PG_PASSWORD: ${PRIVATE_PG_PASSWORD:-password} # Modified this line
    ports:
      - "8000:4000"
    restart: always

volumes:
  postgres_data:
